-- NOTE:
-- The uploaded 02_data.sql does not contain seed INSERT statements.
-- It duplicates the schema definition instead of loading sample data.
-- Keep this file as a placeholder or replace it with actual English INSERT data.
