services:
  postgres:
    image: postgres:16
    container_name: ehotel-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ehotel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d

volumes:
  postgres_data: