spring.application.name=ehotel-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/ehotel
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080